/*
 * HPP-Datein zuerst:
 */

// World:
#include "includes/World.hpp"

//Items:
#include "includes/items.hpp"

//Block
#include  "includes/Block.hpp"

//Player
#include "includes/Player.hpp"

#include "includes/Enemy.hpp"


/*
 * CPP-Datein danach:
 */

// World:
#include "src/World.cpp"

#include "src/Player.cpp"

#include "src/Enemy.cpp"

#include "src/Entity.cpp"

//Items:
#include "src/item/Weapon.cpp"
#include "src/item/Axe.cpp"
#include "src/item/Bow.cpp"
#include "src/item/Sword.cpp"

#include "src/item/Armor.cpp"
#include "src/item/Boots.cpp"
#include "src/item/Chestplate.cpp"
#include "src/item/Helmet.cpp"
#include "src/item/Leggings.cpp"

#include "src/item/RigidItem.cpp"
#include "src/item/Shield.cpp"

#include "src/item/Potion.cpp"

#include "src/item/Material.cpp"
#include "src/item/Rarity.cpp"

#include "src/item/Item.cpp"

//Block
#include  "src/Block.cpp"